layoutfastconfig.example:
  path: '/layoutfastconfig/example'
  defaults:
    _title: 'Example'
    _controller: '\Drupal\layoutfastconfig\Controller\LayoutfastconfigController::build'
  requirements:
    _permission: 'access content'

layoutfastconfig.settings_form:
  path: '/admin/config/system/layoutfastconfig'
  defaults:
    _title: 'LayoutfastConfig settings'
    _form: 'Drupal\layoutfastconfig\Form\SettingsForm'
  requirements:
    _permission: 'administer layoutfastconfig configuration'
